### ISSUE TITLE
Max Amount

### ISSUE THREAD

**Issue by kgordish** [strangerstudios/pmpro-donations#1]
If you choose "other" you are not setting a maximum donation limit.

The text on the webpage reads donation minimum amount to maximum amount.

If you don't set a maximum amount there is still a $ symbol on the webpage.
I wrote "choose the amount to donate" in the maximum line. 
However, the $ symbol was in front of the text and looked odd. 
An option may be to remove $ and have individuals write in.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
