### ISSUE TITLE
Bug: Donations aren't being stored in orders

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-donations#15]
The donation amount is not being stored correctly in member orders. Currently the only way to determine the donation amount is to subtract the subtotal from the total.

Additional Notes:
* Test with various payment gateways

**Comment by pbrocks** [comment]
[This branch calculates and places Donations on Memberslist, Orders, Members CSV and Order Detail page](https://github.com/pbrocks/pmpro-donations/tree/dev-add-to-orders)

**Donations on Memberslist**
![Donations on Memberslist](https://monosnap.com/image/YulXqYLIAnKpj1N2BLCXEN2hShRoeZ.png)

**Donations on Orders**
![Donations on Orders](https://monosnap.com/image/pMrOM6M7sVnwD1vfwFCdVnyeiqJukX.png)

**Donations on Order Detail**
![Donations on Order Detail](https://monosnap.com/image/AcgO5GwXYJ0JuVowqIntUnymMRdlHW.png)

**Comment by andrewlimaza** [comment]
I'd recommend in using `pmpro_formatPrice` for the Member's List column so it would show $30.00 instead of 30.

**Comment by dparker1005** [comment]
Donation amounts are now saved in the order notes.

We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
