### ISSUE TITLE
BUG: Donation amounts are not being charged by PayPal express.

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-donations#18]
When a customer checks out with a donation, the actual amount charged by PayPal does not include the donation. All other indications, including the price seen on the checkout page, at PayPal checkout, and the confirmation page show the donation amount included.

Steps to re-create:

1) under the Payment Settings & SSL tab set the Confirmation Step to "Skip the extra confirmation after users return from PayPal Express"

2) set up a level with donations. Say $100 initial payment.

3) at checkout choose a donation of $25

4) checkout through PayPal

5) after completing checkout, login to the merchant's or customer's PayPal account and check the transaction amount. Instead of being $125 it will only show that $100 was received by the merchant or charged to the customer. All other indications will show $125.

**Comment by dparker1005** [comment]
Testing with the most recent version of PMPro Donations, I was not able to replicate this bug with the steps above.

We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
