### ISSUE TITLE
Feature Request: Display donation value separate from subscription value.

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-donations#25]
A user has requested to display donation values separate from subscription values on the account page and invoices instead of the current combined value.

**Comment by tictag** [comment]
Great idea! I currently have to extract the donation amount from the Order notes in order to export the donation amount into the Orders CSV export. Having the donation amount in metadata would be a far more elegant solution.

Perhaps the same could be done for Gift Aid, which similar to donations also only exists in the Order Notes?

**Comment by dparker1005** [comment]
This is now possible due to the addition of the `pmpro_get_price_parts` filter.

**Comment by MaryOJob** [comment]
Example of the `pmpro_get_price_parts`  filter here, please: https://gist.github.com/dparker1005/6dacc12fc71a05038ab70b950a288c3a

**Comment by dparker1005** [comment]
Closing as this feature has been implemented via filter.
