### ISSUE TITLE
Min and Max Amounts not saving

### ISSUE THREAD

**Issue by OpenEyeMedia** [strangerstudios/pmpro-donations#3]
Hi there - I am unable to save min and max amounts, and if I leave them blank I get the following message during the 'checkout' process:

The highest accepted donation is £. Please enter a new amount.

I am therefore unable to use the donation functionality, as it prevents completion of the registration process unusable.

To confirm I was trying to set the values to 0 and 1000 and did not use any special characters. I also tried with 1 and 1000.

The price dropdown was set to 0,5,10,15,20,other

Thanks in advance for your help, and if you need any additional info, please let me know.
Chris

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
