### ISSUE TITLE
Needs clarity on whether this is *in addition* to using existing Donation add-on

### ISSUE THREAD

**Issue by sensemonster** [strangerstudios/pmpro-donations#41]
Has this development been abandoned please?

As a pmpro licensed user we would like this functionality.  However it is incompatiple when already using the Donation add-on.  The comment in the code states "Allow customers to set an additional donation amount " so it is suggesting suitability for our use case.

**Comment by JarrydLong** [comment]
Hi there, thanks for reaching out. 

This is the repo for the Donations Add On. More details on the Donations Add On can be found over at https://www.paidmembershipspro.com/add-ons/donations-add-on/

If you have any support-related queries, please feel free to reach out to the team over at https://www.paidmembershipspro.com/new-topic/ for further assistance.

**Comment by sensemonster** [comment]
Hi, I have reached out and created a ticket but - surprisingly and unusually - got what I consider to be an unhelpful response :-)

BTW I am still unclear on what "Allow customers to set an *additional* donation amount "  means if it is the same Donation add-on as the one currently available.

**Comment by JarrydLong** [comment]
The Add On allows you to accept donations in two ways. 

1. Create a level that is a 'donation' level. When donating, they only get charged for the donation but their level doesn't change. 
2. Create a level that allows you to add a donation to it. The 'additional' part in the description refers to the donation amount itself being added to the total amount, so members can specify how much they'd like to donate during checkout. 

I'm sorry to hear that you didn't receive a helpful response in one of your tickets. I hope the above helps, if not, please send me a link to that ticket so that I can escalate it for you.

**Comment by sensemonster** [comment]
I really appreciate your time on this Jarryd and I don't want to be critical as the help received so far has been exceptionally good in helping me customise pmpro to the way it is needed to work on our site.  It is just that the charity org I am helping insists on everything being paid for in one single transaction - which is fine when using the Donation add-on.  However they have thrown a "curve ball"  by asking for the ability to ask for a *second* donation type at check-out.  This is what I am working on right now, I have some ideas but not quite there yet with a finished product.  The ticket link is: https://www.paidmembershipspro.com/forums/topic/additional-donation-at-checkout/

**Comment by JarrydLong** [comment]
Thanks for your feedback and for clearing that up for me. I'm going to get back to you on the ticket and we can continue the discussion there. 

Unfortunately, that isn't one of those 'flip a switch' options to add in a second donation, but I can share some options with you and you can decide from there.

**Comment by dparker1005** [comment]
Closing support request as user is being helped in the member forums.
